[package]
name = "vulkano-window"
version = "0.1.0"
authors = ["Federico Frenguelli <synasius@gmail.com>"]

[dependencies]
vulkano = "0.10"
vulkano-shader-derive = "0.10.0"
vulkano-win = "0.10.0"
winit = "0.17"
